version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appliplumeroweb_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/appliplumeroweb
      - PORT=8080
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: appliplumeroweb_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
